#!/usr/bin/env python3
"""Merge the papers' references.bib files into a single thesis.bib.

First occurrence of a key wins; input files are listed newest-first so the
most recently curated entry is kept. Also removes duplicate keys *within* a
single file (bibtex errors on those). Keys whose bodies differ across files
are reported on stderr for one-time manual review.

Usage: python3 tools/merge-bibs.py > thesis.bib
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Newest / most curated first: the winning entry comes from the earliest file.
SOURCES = [
    "papers/paper-multi-width-bv/references.bib",
    "papers/paper-floating-point-in-lean/references.bib",
    "papers/paper-decide-univ-quant-bv/references.bib",
    "papers/collab-paper-lean-bitvectors/references.bib",
    "papers/paper-lean-mlir/references.bib",
    "papers/report-second-year/references.bib",
]

ENTRY_START = re.compile(r"@(\w+)\s*[{(]\s*([^,\s]+)\s*,", re.ASCII)


def parse_entries(text):
    """Yield (kind, key, entry_text) for each @entry in text."""
    for m in ENTRY_START.finditer(text):
        kind = m.group(1).lower()
        if kind in ("comment", "preamble"):
            continue
        # Balance braces starting at the brace right after '@kind'.
        brace_idx = m.start() + len("@") + len(m.group(1))
        while text[brace_idx] not in "{(":
            brace_idx += 1
        depth = 0
        i = brace_idx
        while i < len(text):
            c = text[i]
            if c == "{":
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        yield kind, m.group(2), text[m.start() : i + 1]


def normalize(entry):
    return re.sub(r"\s+", " ", entry).strip()


def main():
    seen = {}       # key -> (entry_text, source)
    strings = []    # @string blocks, kept in order of first appearance
    seen_strings = set()
    differing = {}  # key -> [sources with differing bodies]

    for src in SOURCES:
        path = ROOT / src
        text = path.read_text(encoding="utf-8", errors="replace")
        for kind, key, entry in parse_entries(text):
            if kind == "string":
                norm = normalize(entry)
                if norm not in seen_strings:
                    seen_strings.add(norm)
                    strings.append(entry)
                continue
            if key in seen:
                if normalize(seen[key][0]) != normalize(entry):
                    differing.setdefault(key, [seen[key][1]]).append(src)
                continue
            seen[key] = (entry, src)

    out = sys.stdout
    out.write("%% thesis.bib -- GENERATED by tools/merge-bibs.py; edit additions\n")
    out.write("%% below the marker line, and re-run the script only if a paper's\n")
    out.write("%% references.bib changes (manual additions survive at the bottom).\n\n")
    for s in strings:
        out.write(s + "\n\n")
    for key in sorted(seen, key=str.lower):
        out.write(seen[key][0] + "\n\n")

    print(f"merged {len(seen)} unique entries from {len(SOURCES)} files", file=sys.stderr)
    if differing:
        print(f"{len(differing)} keys had differing bodies (first source won):", file=sys.stderr)
        for key, srcs in sorted(differing.items(), key=lambda kv: kv[0].lower()):
            print(f"  {key}: kept {seen[key][1]}, ignored {', '.join(srcs[1:])}", file=sys.stderr)


if __name__ == "__main__":
    main()
